"""instagram_login_flow_schema

Revision ID: 2cd841529587
Revises: 7d9fb6847e1c
Create Date: 2026-09-21 11:00:57.069206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cd841529587'
down_revision: Union[str, Sequence[str], None] = '7d9fb6847e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instagram_accounts', sa.Column('connection_type', sa.String(), server_default='facebook', nullable=False))
    op.add_column('instagram_accounts', sa.Column('ig_user_access_token', sa.String(), nullable=True))
    op.alter_column('instagram_accounts', 'page_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('instagram_accounts', 'page_access_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instagram_accounts', 'page_access_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('instagram_accounts', 'page_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('instagram_accounts', 'ig_user_access_token')
    op.drop_column('instagram_accounts', 'connection_type')
    # ### end Alembic commands ###
