"""Initial models creation

Revision ID: 2e07bbfdcba3
Revises: 
Create Date: 2026-09-09 14:57:27.500203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e07bbfdcba3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.String(length=36), nullable=True),
    sa.Column('comment_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_logs_action_type'), 'automation_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_automation_logs_comment_id'), 'automation_logs', ['comment_id'], unique=False)
    op.create_index(op.f('ix_automation_logs_created_at'), 'automation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_automation_logs_id'), 'automation_logs', ['id'], unique=False)
    op.create_table('comment_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.String(), nullable=False),
    sa.Column('media_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('commenter_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_events_comment_id'), 'comment_events', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comment_events_id'), 'comment_events', ['id'], unique=False)
    op.create_index(op.f('ix_comment_events_media_id'), 'comment_events', ['media_id'], unique=False)
    op.create_table('facebook_comment_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.String(), nullable=False),
    sa.Column('media_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('commenter_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facebook_comment_events_comment_id'), 'facebook_comment_events', ['comment_id'], unique=False)
    op.create_index(op.f('ix_facebook_comment_events_id'), 'facebook_comment_events', ['id'], unique=False)
    op.create_index(op.f('ix_facebook_comment_events_media_id'), 'facebook_comment_events', ['media_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('facebook_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('facebook_page_id', sa.String(), nullable=False),
    sa.Column('page_access_token', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('profile_picture_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facebook_accounts_facebook_page_id'), 'facebook_accounts', ['facebook_page_id'], unique=True)
    op.create_index(op.f('ix_facebook_accounts_id'), 'facebook_accounts', ['id'], unique=False)
    op.create_table('instagram_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instagram_business_account_id', sa.String(), nullable=False),
    sa.Column('page_id', sa.String(), nullable=False),
    sa.Column('page_access_token', sa.String(), nullable=False),
    sa.Column('user_access_token', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('profile_picture_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instagram_accounts_id'), 'instagram_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_instagram_accounts_instagram_business_account_id'), 'instagram_accounts', ['instagram_business_account_id'], unique=True)
    op.create_index(op.f('ix_instagram_accounts_page_id'), 'instagram_accounts', ['page_id'], unique=False)
    op.create_table('dm_automations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('instagram_account_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('trigger_type', sa.String(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('reply_text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facebook_posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('facebook_account_id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('automation_status', sa.String(), nullable=True),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('reply_message', sa.Text(), nullable=True),
    sa.Column('dm_message', sa.Text(), nullable=True),
    sa.Column('is_future_post', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['facebook_account_id'], ['facebook_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facebook_posts_id'), 'facebook_posts', ['id'], unique=False)
    op.create_table('ig_conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instagram_account_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.String(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ig_conversations_id'), 'ig_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_ig_conversations_participant_id'), 'ig_conversations', ['participant_id'], unique=False)
    op.create_table('ig_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instagram_account_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('recipient_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ig_messages_id'), 'ig_messages', ['id'], unique=False)
    op.create_index(op.f('ix_ig_messages_recipient_id'), 'ig_messages', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_ig_messages_sender_id'), 'ig_messages', ['sender_id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instagram_account_id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('automation_status', sa.String(), nullable=True),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('reply_message', sa.Text(), nullable=True),
    sa.Column('dm_message', sa.Text(), nullable=True),
    sa.Column('is_future_post', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_table('automation_flows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('instagram_account_id', sa.Integer(), nullable=True),
    sa.Column('facebook_account_id', sa.Integer(), nullable=True),
    sa.Column('instagram_post_id', sa.String(), nullable=True),
    sa.Column('facebook_post_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_future_flow', sa.Boolean(), nullable=False),
    sa.Column('future_post_caption', sa.Text(), nullable=True),
    sa.Column('future_post_scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('future_flow_status', sa.String(length=20), nullable=True),
    sa.Column('future_flow_last_scanned_at', sa.DateTime(), nullable=True),
    sa.Column('apply_to_all_future_posts', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['facebook_account_id'], ['facebook_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['facebook_post_id'], ['facebook_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instagram_post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('media_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_table('dm_automation_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('automation_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['automation_id'], ['dm_automations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['ig_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facebook_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('media_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['facebook_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facebook_comments_id'), 'facebook_comments', ['id'], unique=False)
    op.create_table('flow_edges',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('flow_id', sa.String(length=36), nullable=False),
    sa.Column('source_node_id', sa.String(length=50), nullable=False),
    sa.Column('target_node_id', sa.String(length=50), nullable=False),
    sa.Column('condition_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['automation_flows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flow_nodes',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('flow_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['automation_flows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flow_nodes')
    op.drop_table('flow_edges')
    op.drop_index(op.f('ix_facebook_comments_id'), table_name='facebook_comments')
    op.drop_table('facebook_comments')
    op.drop_table('dm_automation_executions')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_table('automation_flows')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_ig_messages_sender_id'), table_name='ig_messages')
    op.drop_index(op.f('ix_ig_messages_recipient_id'), table_name='ig_messages')
    op.drop_index(op.f('ix_ig_messages_id'), table_name='ig_messages')
    op.drop_table('ig_messages')
    op.drop_index(op.f('ix_ig_conversations_participant_id'), table_name='ig_conversations')
    op.drop_index(op.f('ix_ig_conversations_id'), table_name='ig_conversations')
    op.drop_table('ig_conversations')
    op.drop_index(op.f('ix_facebook_posts_id'), table_name='facebook_posts')
    op.drop_table('facebook_posts')
    op.drop_table('dm_automations')
    op.drop_index(op.f('ix_instagram_accounts_page_id'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_instagram_business_account_id'), table_name='instagram_accounts')
    op.drop_index(op.f('ix_instagram_accounts_id'), table_name='instagram_accounts')
    op.drop_table('instagram_accounts')
    op.drop_index(op.f('ix_facebook_accounts_id'), table_name='facebook_accounts')
    op.drop_index(op.f('ix_facebook_accounts_facebook_page_id'), table_name='facebook_accounts')
    op.drop_table('facebook_accounts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_facebook_comment_events_media_id'), table_name='facebook_comment_events')
    op.drop_index(op.f('ix_facebook_comment_events_id'), table_name='facebook_comment_events')
    op.drop_index(op.f('ix_facebook_comment_events_comment_id'), table_name='facebook_comment_events')
    op.drop_table('facebook_comment_events')
    op.drop_index(op.f('ix_comment_events_media_id'), table_name='comment_events')
    op.drop_index(op.f('ix_comment_events_id'), table_name='comment_events')
    op.drop_index(op.f('ix_comment_events_comment_id'), table_name='comment_events')
    op.drop_table('comment_events')
    op.drop_index(op.f('ix_automation_logs_id'), table_name='automation_logs')
    op.drop_index(op.f('ix_automation_logs_created_at'), table_name='automation_logs')
    op.drop_index(op.f('ix_automation_logs_comment_id'), table_name='automation_logs')
    op.drop_index(op.f('ix_automation_logs_action_type'), table_name='automation_logs')
    op.drop_table('automation_logs')
    # ### end Alembic commands ###
