"""remove_legacy_simple_automation_fields

Revision ID: 7d9fb6847e1c
Revises: 2e07bbfdcba3
Create Date: 2026-09-20 17:22:05.078404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d9fb6847e1c'
down_revision: Union[str, Sequence[str], None] = '2e07bbfdcba3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dm_automation_executions_message_id_fkey', 'dm_automation_executions', type_='foreignkey')
    op.drop_index('ix_ig_messages_id', table_name='ig_messages')
    op.drop_index('ix_ig_messages_recipient_id', table_name='ig_messages')
    op.drop_index('ix_ig_messages_sender_id', table_name='ig_messages')
    op.drop_table('ig_messages')
    op.drop_index('ix_ig_conversations_id', table_name='ig_conversations')
    op.drop_index('ix_ig_conversations_participant_id', table_name='ig_conversations')
    op.drop_table('ig_conversations')
    op.drop_column('facebook_posts', 'keyword')
    op.drop_column('facebook_posts', 'dm_message')
    op.drop_column('facebook_posts', 'reply_message')
    op.drop_column('posts', 'keyword')
    op.drop_column('posts', 'dm_message')
    op.drop_column('posts', 'reply_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('reply_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('dm_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('keyword', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('facebook_posts', sa.Column('reply_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('facebook_posts', sa.Column('dm_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('facebook_posts', sa.Column('keyword', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('dm_automation_executions_message_id_fkey', 'dm_automation_executions', 'ig_messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.create_table('ig_conversations',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('instagram_account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('participant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_message_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], name='ig_conversations_instagram_account_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ig_conversations_pkey')
    )
    op.create_index('ix_ig_conversations_participant_id', 'ig_conversations', ['participant_id'], unique=False)
    op.create_index('ix_ig_conversations_id', 'ig_conversations', ['id'], unique=False)
    op.create_table('ig_messages',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('instagram_account_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('recipient_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['instagram_account_id'], ['instagram_accounts.id'], name='ig_messages_instagram_account_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ig_messages_pkey')
    )
    op.create_index('ix_ig_messages_sender_id', 'ig_messages', ['sender_id'], unique=False)
    op.create_index('ix_ig_messages_recipient_id', 'ig_messages', ['recipient_id'], unique=False)
    op.create_index('ix_ig_messages_id', 'ig_messages', ['id'], unique=False)
    # ### end Alembic commands ###
